### ISSUE TITLE
Installation of pycddlib dependency on MacOS

### ISSUE THREAD

**Issue by alphaville** [stephane-caron/pypoman#6]
I tried to install `pypoman` on MacOS v11.6 within a virtual environment with Python version 3.8.9. I started by installing `cython` and `gplk` using:

```
brew install cython
brew install gplk
``` 

and then installed `scipy` with `pip install scipy`. However, `pip install pypoman` gives the following error 

```
$ pip install pypoman
Collecting pypoman
  Using cached pypoman-0.5.4-py3-none-any.whl
Collecting pycddlib
  Using cached pycddlib-2.1.4.tar.gz (265 kB)
  Preparing metadata (setup.py) ... done
Collecting cvxopt
  Using cached cvxopt-1.2.7-cp38-cp38-macosx_10_9_x86_64.whl (3.1 MB)
Building wheels for collected packages: pycddlib
  Building wheel for pycddlib (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/3054363/PycharmProjects/setz/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/setup.py'"'"'; __file__='"'"'/private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-wheel-6ht_j0yq
       cwd: /private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/
  Complete output (29 lines):
  /Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/__init__.py:148: SetuptoolsDeprecationWarning: setup_requires is deprecated. Supply build dependencies using PEP 517 pyproject.toml build-requires.
    warnings.warn(
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/setup.py", line 107, in <module>
      setup(
    File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 158, in setup
      _install_setup_requires(attrs)
    File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/dist.py", line 806, in fetch_build_eggs
      resolved_dists = pkg_resources.working_set.resolve(
    File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 766, in resolve
      dist = best[req.key] = env.best_match(
    File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1051, in best_match
      return self.obtain(req, installer)
    File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1063, in obtain
      return installer(requirement)
    File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/dist.py", line 877, in fetch_build_egg
      return fetch_build_egg(self, req)
    File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/installer.py", line 80, in fetch_build_egg
      wheel.install_as_egg(dist_location)
    File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/wheel.py", line 95, in install_as_egg
      self._install_as_egg(destination_eggdir, zf)
    File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/wheel.py", line 103, in _install_as_egg
      self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
    File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/wheel.py", line 124, in _convert_metadata
      os.mkdir(destination_eggdir)
  FileExistsError: [Errno 17] File exists: '/private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/.eggs/Cython-0.29.24-py3.8-macosx-10.14-x86_64.egg'
  ----------------------------------------
  ERROR: Failed building wheel for pycddlib
  Running setup.py clean for pycddlib
  ERROR: Command errored out with exit status 1:
   command: /Users/3054363/PycharmProjects/setz/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/setup.py'"'"'; __file__='"'"'/private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32
  Complete output (29 lines):
  /Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/__init__.py:148: SetuptoolsDeprecationWarning: setup_requires is deprecated. Supply build dependencies using PEP 517 pyproject.toml build-requires.
    warnings.warn(
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/setup.py", line 107, in <module>
      setup(
    File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 158, in setup
      _install_setup_requires(attrs)
    File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/dist.py", line 806, in fetch_build_eggs
      resolved_dists = pkg_resources.working_set.resolve(
    File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 766, in resolve
      dist = best[req.key] = env.best_match(
    File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1051, in best_match
      return self.obtain(req, installer)
    File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1063, in obtain
      return installer(requirement)
    File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/dist.py", line 877, in fetch_build_egg
      return fetch_build_egg(self, req)
    File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/installer.py", line 80, in fetch_build_egg
      wheel.install_as_egg(dist_location)
    File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/wheel.py", line 95, in install_as_egg
      self._install_as_egg(destination_eggdir, zf)
    File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/wheel.py", line 103, in _install_as_egg
      self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
    File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/wheel.py", line 124, in _convert_metadata
      os.mkdir(destination_eggdir)
  FileExistsError: [Errno 17] File exists: '/private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/.eggs/Cython-0.29.24-py3.8-macosx-10.14-x86_64.egg'
  ----------------------------------------
  ERROR: Failed cleaning build dir for pycddlib
Failed to build pycddlib
Installing collected packages: pycddlib, cvxopt, pypoman
    Running setup.py install for pycddlib ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/3054363/PycharmProjects/setz/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/setup.py'"'"'; __file__='"'"'/private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-record-0zuwcfj8/install-record.txt --single-version-externally-managed --compile --install-headers /Users/3054363/PycharmProjects/setz/venv/include/site/python3.8/pycddlib
         cwd: /private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/
    Complete output (29 lines):
    /Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/__init__.py:148: SetuptoolsDeprecationWarning: setup_requires is deprecated. Supply build dependencies using PEP 517 pyproject.toml build-requires.
      warnings.warn(
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/setup.py", line 107, in <module>
        setup(
      File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 158, in setup
        _install_setup_requires(attrs)
      File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/dist.py", line 806, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 766, in resolve
        dist = best[req.key] = env.best_match(
      File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1051, in best_match
        return self.obtain(req, installer)
      File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1063, in obtain
        return installer(requirement)
      File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/dist.py", line 877, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/installer.py", line 80, in fetch_build_egg
        wheel.install_as_egg(dist_location)
      File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/wheel.py", line 95, in install_as_egg
        self._install_as_egg(destination_eggdir, zf)
      File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/wheel.py", line 103, in _install_as_egg
        self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
      File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/wheel.py", line 124, in _convert_metadata
        os.mkdir(destination_eggdir)
    FileExistsError: [Errno 17] File exists: '/private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/.eggs/Cython-0.29.24-py3.8-macosx-10.14-x86_64.egg'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/3054363/PycharmProjects/setz/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/setup.py'"'"'; __file__='"'"'/private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-record-0zuwcfj8/install-record.txt --single-version-externally-managed --compile --install-headers /Users/3054363/PycharmProjects/setz/venv/include/site/python3.8/pycddlib Check the logs for full command output.
```

**Comment by stephane-caron** [comment]
From your log, the main error is that pip fails to build pycddlib which is a key dependency for pypoman. Let's continue the investigation in https://github.com/mcmtroffaes/pycddlib/issues/49

**Comment by davidaino** [comment]
Dear @stephane-caron, I tried to install pypoman on a MacOS 11.6 with Python 3.8.
I didn't get any problem during the installation but when I try to run your example program I get the following message:
File "/Users/user1/.conda/envs/ExtremePoints/lib/python3.8/site-packages/pypoman/duality.py", line 120, in compute_polytope_vertices
    mat = cdd.Matrix(hstack([b, -A]), number_type='float')
AttributeError: module 'cdd' has no attribute 'Matrix'

What am I doing wrong? I thank you in advance for your help.

**Comment by stephane-caron** [comment]
@davidaino this seems like a different problem than the original question from @alphaville. Can you open a separate issue for it?

In your issue description, please include the output of:
```python
import cdd
print(cdd.__version__)
```

**Comment by stephane-caron** [comment]
Closing this issue as https://github.com/mcmtroffaes/pycddlib/issues/49 has been closed now.
